name: MRG_Ubuntu

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        include:
          - compiler: clang++
            CONAN_COMPILER: clang
          - compiler: g++
            CONAN_COMPILER: gcc

    steps:
    - uses: actions/checkout@v2

    # Installing the Vulkan SDK
    - name: Install Vulkan SDK
      shell: bash
      run: |
        wget -qO - https://packages.lunarg.com/lunarg-signing-key-pub.asc | sudo apt-key add -
        sudo wget -qO /etc/apt/sources.list.d/lunarg-vulkan-1.2.154-focal.list https://packages.lunarg.com/vulkan/1.2.154/lunarg-vulkan-1.2.154-focal.list
        sudo apt update
        sudo apt install vulkan-sdk
    
    - name: Create Build Environment
      working-directory: ${{runner.workspace}}/Morrigu
      shell: bash
      run: mkdir build

    # Conan setup
    - name: Install conan
      shell: bash
      run: pip3 install conan

    - name: add conan to path
      shell: bash
      run: echo "::add-path::~/.local/bin"
    
    - name: configure conan new profile
      shell: bash
      run: conan profile new default --detect
    
    - name: configure conan C++ compiler
      shell: bash
      run: |
        conan profile update settings.compiler.libcxx=libstdc++11 default
        conan profile update settings.compiler=${{ matrix.CONAN_COMPILER }} default
        conan profile update settings.compiler.version=9 default
        conan profile update env.CXX=${{ matrix.compiler }}-9 default
    
    - name: add conan remotes
      shell: bash
      run: |
        conan remote add bincrafters https://api.bintray.com/conan/bincrafters/public-conan
        conan remote add ImGui-Docking https://api.bintray.com/conan/ithyx/imgui
    
    - name: conan install [DEBUG]
      shell: bash
      working-directory: ${{runner.workspace}}/Morrigu/build
      run: conan install .. -s build_type=Debug --build=missing
    
    - name: conan install [Release]
      shell: bash
      working-directory: ${{runner.workspace}}/Morrigu/build
      run: conan install .. -s build_type=Release --build=missing

    # Cmake setup
    - name: Configure CMake [DEBUG]
      shell: bash
      working-directory: ${{runner.workspace}}/Morrigu/build
      run: cmake .. -DCMAKE_BUILD_TYPE=Debug
      env:
        CXX: ${{ matrix.compiler }}-9
    
    - name: Build [DEBUG]
      working-directory: ${{runner.workspace}}/Morrigu/build
      shell: bash
      run: cmake --build .
      env:
        CXX: ${{ matrix.compiler }}-9
    
    - name: Configure CMake [RELEASE]
      shell: bash
      working-directory: ${{runner.workspace}}/Morrigu/build
      run: cmake .. -DCMAKE_BUILD_TYPE=Release
      env:
        CXX: ${{ matrix.compiler }}-9

    - name: Build [RELEASE]
      working-directory: ${{runner.workspace}}/Morrigu/build
      shell: bash
      run: cmake --build .
      env:
        CXX: ${{ matrix.compiler }}-9
